wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1651596565
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      4: 3.9.5
      5: 0.12.11
      6: 4.15.0
      8:
      - 1
      - 3
      - 5
